// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collection} from '../models';
import {config} from '../models';
import {cookiejar} from '../models';
import {history} from '../models';
import {app} from '../models';
import {runner} from '../models';

export function ClearCookies():Promise<void>;

export function ClearHistory():Promise<void>;

export function CreateFolder(arg1:string,arg2:string):Promise<void>;

export function CreateRequest(arg1:string,arg2:string,arg3:string):Promise<collection.Request>;

export function DeleteEnv(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteRequest(arg1:string):Promise<void>;

export function DeleteResponseExample(arg1:string,arg2:string):Promise<void>;

export function GetSettings():Promise<config.Settings>;

export function ListCookies():Promise<Array<cookiejar.Info>>;

export function ListEnvs():Promise<Array<collection.Env>>;

export function ListHistory(arg1:number):Promise<Array<history.Entry>>;

export function ListResponseExamples(arg1:string):Promise<Array<collection.ResponseExample>>;

export function OpenCollection(arg1:string):Promise<collection.CollectionInfo>;

export function PickDirectory():Promise<string>;

export function Quit():Promise<void>;

export function ReadRequest(arg1:string):Promise<collection.Request>;

export function ReloadCollection():Promise<collection.CollectionInfo>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function RenameRequest(arg1:string,arg2:string):Promise<void>;

export function ResolveText(arg1:string,arg2:string):Promise<app.ResolveResult>;

export function SaveEnv(arg1:collection.Env):Promise<void>;

export function SaveRequest(arg1:collection.Request):Promise<void>;

export function SaveResponseExample(arg1:collection.Request,arg2:string,arg3:runner.Result):Promise<collection.ResponseExample>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SendRequest(arg1:collection.Request,arg2:string):Promise<runner.Result>;

export function SetHeadlessDir(arg1:string):Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
