// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collection} from '../models';
import {app} from '../models';
import {runner} from '../models';

export function CreateFolder(arg1:string):Promise<void>;

export function CreateRequest(arg1:string,arg2:string,arg3:string):Promise<collection.Request>;

export function DeleteEnv(arg1:string):Promise<void>;

export function DeleteRequest(arg1:string):Promise<void>;

export function ListEnvs():Promise<Array<collection.Env>>;

export function OpenCollection(arg1:string):Promise<collection.CollectionInfo>;

export function PickDirectory():Promise<string>;

export function ReadRequest(arg1:string):Promise<collection.Request>;

export function ReloadCollection():Promise<collection.CollectionInfo>;

export function ResolveText(arg1:string,arg2:string):Promise<app.ResolveResult>;

export function SaveEnv(arg1:collection.Env):Promise<void>;

export function SaveRequest(arg1:collection.Request):Promise<void>;

export function SendRequest(arg1:collection.Request,arg2:string):Promise<runner.Result>;

export function SetHeadlessDir(arg1:string):Promise<void>;
