// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyMCPSettings() {
  return window['go']['app']['App']['ApplyMCPSettings']();
}

export function CancelSend(arg1) {
  return window['go']['app']['App']['CancelSend'](arg1);
}

export function ClearCookies() {
  return window['go']['app']['App']['ClearCookies']();
}

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function CreateDoc(arg1) {
  return window['go']['app']['App']['CreateDoc'](arg1);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['app']['App']['CreateFolder'](arg1, arg2);
}

export function CreateRequest(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateRequest'](arg1, arg2, arg3);
}

export function CreateRequestFromDraft(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateRequestFromDraft'](arg1, arg2, arg3);
}

export function DeleteCookie(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteCookie'](arg1, arg2, arg3);
}

export function DeleteDoc(arg1) {
  return window['go']['app']['App']['DeleteDoc'](arg1);
}

export function DeleteEnv(arg1) {
  return window['go']['app']['App']['DeleteEnv'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['app']['App']['DeleteFolder'](arg1);
}

export function DeleteRequest(arg1) {
  return window['go']['app']['App']['DeleteRequest'](arg1);
}

export function DeleteResponseExample(arg1, arg2) {
  return window['go']['app']['App']['DeleteResponseExample'](arg1, arg2);
}

export function ExportDoc(arg1, arg2) {
  return window['go']['app']['App']['ExportDoc'](arg1, arg2);
}

export function GenerateCode(arg1, arg2, arg3) {
  return window['go']['app']['App']['GenerateCode'](arg1, arg2, arg3);
}

export function GetGrpcDefault() {
  return window['go']['app']['App']['GetGrpcDefault']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetSyncBind() {
  return window['go']['app']['App']['GetSyncBind']();
}

export function GetSyncStatus() {
  return window['go']['app']['App']['GetSyncStatus']();
}

export function GrpcMessageFields(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GrpcMessageFields'](arg1, arg2, arg3, arg4);
}

export function GrpcSampleMessage(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GrpcSampleMessage'](arg1, arg2, arg3, arg4);
}

export function GrpcValidateMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GrpcValidateMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function ImportBrunoDir(arg1) {
  return window['go']['app']['App']['ImportBrunoDir'](arg1);
}

export function ImportCollection(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportCollection'](arg1, arg2, arg3);
}

export function ImportGrpcProtos(arg1, arg2) {
  return window['go']['app']['App']['ImportGrpcProtos'](arg1, arg2);
}

export function ListConflicts() {
  return window['go']['app']['App']['ListConflicts']();
}

export function ListCookies() {
  return window['go']['app']['App']['ListCookies']();
}

export function ListDocs() {
  return window['go']['app']['App']['ListDocs']();
}

export function ListEnvs() {
  return window['go']['app']['App']['ListEnvs']();
}

export function ListGrpcProtos() {
  return window['go']['app']['App']['ListGrpcProtos']();
}

export function ListHistory(arg1) {
  return window['go']['app']['App']['ListHistory'](arg1);
}

export function ListResponseExamples(arg1) {
  return window['go']['app']['App']['ListResponseExamples'](arg1);
}

export function LoadGrpcSchema(arg1, arg2) {
  return window['go']['app']['App']['LoadGrpcSchema'](arg1, arg2);
}

export function MCPStatusText() {
  return window['go']['app']['App']['MCPStatusText']();
}

export function MockStatus() {
  return window['go']['app']['App']['MockStatus']();
}

export function MoveFolder(arg1, arg2) {
  return window['go']['app']['App']['MoveFolder'](arg1, arg2);
}

export function MoveRequest(arg1, arg2) {
  return window['go']['app']['App']['MoveRequest'](arg1, arg2);
}

export function OpenCollection(arg1) {
  return window['go']['app']['App']['OpenCollection'](arg1);
}

export function ParseCurl(arg1) {
  return window['go']['app']['App']['ParseCurl'](arg1);
}

export function PickDirectory() {
  return window['go']['app']['App']['PickDirectory']();
}

export function PickFile() {
  return window['go']['app']['App']['PickFile']();
}

export function PickGrpcProtoFiles() {
  return window['go']['app']['App']['PickGrpcProtoFiles']();
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function ReadDoc(arg1) {
  return window['go']['app']['App']['ReadDoc'](arg1);
}

export function ReadRequest(arg1) {
  return window['go']['app']['App']['ReadRequest'](arg1);
}

export function RebuildIndex() {
  return window['go']['app']['App']['RebuildIndex']();
}

export function RegenerateMCPToken() {
  return window['go']['app']['App']['RegenerateMCPToken']();
}

export function ReloadCollection() {
  return window['go']['app']['App']['ReloadCollection']();
}

export function RemoveGrpcProto(arg1) {
  return window['go']['app']['App']['RemoveGrpcProto'](arg1);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['app']['App']['RenameFolder'](arg1, arg2);
}

export function RenameRequest(arg1, arg2) {
  return window['go']['app']['App']['RenameRequest'](arg1, arg2);
}

export function ReplayHistory(arg1, arg2) {
  return window['go']['app']['App']['ReplayHistory'](arg1, arg2);
}

export function ResolveConflict(arg1, arg2) {
  return window['go']['app']['App']['ResolveConflict'](arg1, arg2);
}

export function ResolveText(arg1, arg2) {
  return window['go']['app']['App']['ResolveText'](arg1, arg2);
}

export function RunSync(arg1) {
  return window['go']['app']['App']['RunSync'](arg1);
}

export function SaveDoc(arg1) {
  return window['go']['app']['App']['SaveDoc'](arg1);
}

export function SaveEnv(arg1) {
  return window['go']['app']['App']['SaveEnv'](arg1);
}

export function SaveRequest(arg1) {
  return window['go']['app']['App']['SaveRequest'](arg1);
}

export function SaveResponseBody(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveResponseBody'](arg1, arg2, arg3);
}

export function SaveResponseExample(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveResponseExample'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SearchIndex(arg1, arg2) {
  return window['go']['app']['App']['SearchIndex'](arg1, arg2);
}

export function SendRequest(arg1, arg2) {
  return window['go']['app']['App']['SendRequest'](arg1, arg2);
}

export function SetGrpcDefault(arg1, arg2) {
  return window['go']['app']['App']['SetGrpcDefault'](arg1, arg2);
}

export function SetHeadlessDir(arg1) {
  return window['go']['app']['App']['SetHeadlessDir'](arg1);
}

export function SetMCPBackend(arg1) {
  return window['go']['app']['App']['SetMCPBackend'](arg1);
}

export function SetSyncBind(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SetSyncBind'](arg1, arg2, arg3, arg4);
}

export function StartAutoSync(arg1) {
  return window['go']['app']['App']['StartAutoSync'](arg1);
}

export function StartMock(arg1) {
  return window['go']['app']['App']['StartMock'](arg1);
}

export function StopAutoSync() {
  return window['go']['app']['App']['StopAutoSync']();
}

export function StopMock() {
  return window['go']['app']['App']['StopMock']();
}

export function SubscribeEvents() {
  return window['go']['app']['App']['SubscribeEvents']();
}

export function SyncDocAssets(arg1) {
  return window['go']['app']['App']['SyncDocAssets'](arg1);
}

export function UnbindSync() {
  return window['go']['app']['App']['UnbindSync']();
}

export function WindowIsMaximised() {
  return window['go']['app']['App']['WindowIsMaximised']();
}

export function WindowMinimise() {
  return window['go']['app']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['app']['App']['WindowToggleMaximise']();
}
