// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCookies() {
  return window['go']['app']['App']['ClearCookies']();
}

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function CreateFolder(arg1) {
  return window['go']['app']['App']['CreateFolder'](arg1);
}

export function CreateRequest(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateRequest'](arg1, arg2, arg3);
}

export function DeleteEnv(arg1) {
  return window['go']['app']['App']['DeleteEnv'](arg1);
}

export function DeleteRequest(arg1) {
  return window['go']['app']['App']['DeleteRequest'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function ListCookies() {
  return window['go']['app']['App']['ListCookies']();
}

export function ListEnvs() {
  return window['go']['app']['App']['ListEnvs']();
}

export function ListHistory(arg1) {
  return window['go']['app']['App']['ListHistory'](arg1);
}

export function OpenCollection(arg1) {
  return window['go']['app']['App']['OpenCollection'](arg1);
}

export function PickDirectory() {
  return window['go']['app']['App']['PickDirectory']();
}

export function ReadRequest(arg1) {
  return window['go']['app']['App']['ReadRequest'](arg1);
}

export function ReloadCollection() {
  return window['go']['app']['App']['ReloadCollection']();
}

export function ResolveText(arg1, arg2) {
  return window['go']['app']['App']['ResolveText'](arg1, arg2);
}

export function SaveEnv(arg1) {
  return window['go']['app']['App']['SaveEnv'](arg1);
}

export function SaveRequest(arg1) {
  return window['go']['app']['App']['SaveRequest'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SendRequest(arg1, arg2) {
  return window['go']['app']['App']['SendRequest'](arg1, arg2);
}

export function SetHeadlessDir(arg1) {
  return window['go']['app']['App']['SetHeadlessDir'](arg1);
}
