// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collection} from '../models';
import {app} from '../models';
import {config} from '../models';
import {syncengine} from '../models';
import {proto} from '../models';
import {cookiejar} from '../models';
import {history} from '../models';
import {mocksrv} from '../models';
import {runner} from '../models';
import {index} from '../models';

export function CancelSend(arg1:string):Promise<void>;

export function ClearCookies():Promise<void>;

export function ClearHistory():Promise<void>;

export function CreateDoc(arg1:string):Promise<collection.DocEntry>;

export function CreateFolder(arg1:string,arg2:string):Promise<void>;

export function CreateRequest(arg1:string,arg2:string,arg3:string):Promise<collection.Request>;

export function CreateRequestFromDraft(arg1:string,arg2:string,arg3:collection.Request):Promise<collection.Request>;

export function DeleteCookie(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteDoc(arg1:string):Promise<void>;

export function DeleteEnv(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteRequest(arg1:string):Promise<void>;

export function DeleteResponseExample(arg1:string,arg2:string):Promise<void>;

export function ExportDoc(arg1:string,arg2:string):Promise<string>;

export function GenerateCode(arg1:string,arg2:string,arg3:collection.Request):Promise<string>;

export function GetGrpcDefault():Promise<app.GrpcDefaultInfo>;

export function GetSettings():Promise<config.Settings>;

export function GetSyncBind():Promise<syncengine.BindInfo>;

export function GetSyncStatus():Promise<app.SyncStatus>;

export function GrpcMessageFields(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<Array<proto.FieldInfo>>;

export function GrpcSampleMessage(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<string>;

export function GrpcValidateMessage(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ImportBrunoDir(arg1:string):Promise<collection.ImportSummary>;

export function ImportCollection(arg1:string,arg2:string,arg3:string):Promise<collection.ImportSummary>;

export function ImportGrpcProtos(arg1:Array<string>,arg2:Array<string>):Promise<app.GrpcSchemaInfo>;

export function ListConflicts():Promise<Array<collection.ConflictItem>>;

export function ListCookies():Promise<Array<cookiejar.Info>>;

export function ListDocs():Promise<Array<collection.DocEntry>>;

export function ListEnvs():Promise<Array<collection.Env>>;

export function ListGrpcProtos():Promise<Array<collection.ProtoFileInfo>>;

export function ListHistory(arg1:number):Promise<Array<history.Entry>>;

export function ListResponseExamples(arg1:string):Promise<Array<collection.ResponseExample>>;

export function LoadGrpcSchema(arg1:string,arg2:Array<string>):Promise<app.GrpcSchemaInfo>;

export function MockStatus():Promise<mocksrv.Status>;

export function MoveFolder(arg1:string,arg2:string):Promise<void>;

export function MoveRequest(arg1:string,arg2:string):Promise<void>;

export function OpenCollection(arg1:string):Promise<collection.CollectionInfo>;

export function ParseCurl(arg1:string):Promise<collection.Request>;

export function PickDirectory():Promise<string>;

export function PickFile():Promise<string>;

export function PickGrpcProtoFiles():Promise<Array<string>>;

export function Quit():Promise<void>;

export function ReadDoc(arg1:string):Promise<collection.DocEntry>;

export function ReadRequest(arg1:string):Promise<collection.Request>;

export function RebuildIndex():Promise<void>;

export function ReloadCollection():Promise<collection.CollectionInfo>;

export function RemoveGrpcProto(arg1:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function RenameRequest(arg1:string,arg2:string):Promise<void>;

export function ReplayHistory(arg1:number,arg2:string):Promise<runner.Result>;

export function ResolveConflict(arg1:string,arg2:string):Promise<void>;

export function ResolveText(arg1:string,arg2:string):Promise<app.ResolveResult>;

export function RunSync(arg1:string):Promise<syncengine.Report>;

export function SaveDoc(arg1:collection.DocEntry):Promise<void>;

export function SaveEnv(arg1:collection.Env):Promise<void>;

export function SaveRequest(arg1:collection.Request):Promise<void>;

export function SaveResponseBody(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function SaveResponseExample(arg1:collection.Request,arg2:string,arg3:runner.Result):Promise<collection.ResponseExample>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SearchIndex(arg1:string,arg2:number):Promise<Array<index.Node>>;

export function SendRequest(arg1:collection.Request,arg2:string):Promise<runner.Result>;

export function SetGrpcDefault(arg1:string,arg2:Array<string>):Promise<void>;

export function SetHeadlessDir(arg1:string):Promise<void>;

export function SetSyncBind(arg1:string,arg2:number,arg3:string,arg4:string):Promise<syncengine.BindInfo>;

export function StartAutoSync(arg1:number):Promise<void>;

export function StartMock(arg1:number):Promise<mocksrv.Status>;

export function StopAutoSync():Promise<void>;

export function StopMock():Promise<void>;

export function SubscribeEvents():Promise<any|any>;

export function SyncDocAssets(arg1:string):Promise<number>;

export function UnbindSync():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
