// Package mocksrv 本地 Mock 服务（H7）：按集合请求的「方法+路径」匹配，回放示例或合成响应。
// 匹配语义与共享包 share/mock 一致，避免与服务端 Mock 命中结果不一致。
package mocksrv

import (
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"sync"
	"time"

	"api-doc-go-client/internal/collection"
	"github.com/leihenshang/api-doc-go-share/mock"
)

// Server 本地 Mock HTTP 服务。
type Server struct {
	mu     sync.Mutex
	ln     net.Listener
	srv    *http.Server
	coll   *collection.Collection
	port   int
	reqCnt int
}

// Status 运行状态（给 UI 展示）。
type Status struct {
	Running bool   `json:"running"`
	Port    int    `json:"port"`
	URL     string `json:"url"`
	Hits    int    `json:"hits"`
}

// New 创建 Mock 服务（未启动）。
func New(c *collection.Collection) *Server {
	return &Server{coll: c}
}

// Start 在 port 启动（port<=0 时随机端口）。
func (s *Server) Start(port int) (*Status, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.srv != nil {
		return s.statusLocked(), nil
	}
	addr := fmt.Sprintf("127.0.0.1:%d", port)
	ln, err := net.Listen("tcp", addr)
	if err != nil {
		return nil, fmt.Errorf("启动 Mock 失败: %w", err)
	}
	s.ln = ln
	s.port = ln.Addr().(*net.TCPAddr).Port
	s.srv = &http.Server{Handler: http.HandlerFunc(s.handle)}
	go func() { _ = s.srv.Serve(ln) }()
	return s.statusLocked(), nil
}

// Stop 停止服务。
func (s *Server) Stop() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.srv == nil {
		return nil
	}
	err := s.srv.Close()
	s.srv, s.ln = nil, nil
	return err
}

// Status 当前状态。
func (s *Server) Status() *Status {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.statusLocked()
}

func (s *Server) statusLocked() *Status {
	if s.srv == nil {
		return &Status{Running: false}
	}
	return &Status{
		Running: true,
		Port:    s.port,
		URL:     fmt.Sprintf("http://127.0.0.1:%d", s.port),
		Hits:    s.reqCnt,
	}
}

func (s *Server) handle(w http.ResponseWriter, r *http.Request) {
	s.mu.Lock()
	s.reqCnt++
	c := s.coll
	s.mu.Unlock()
	if c == nil {
		http.Error(w, "no collection", 500)
		return
	}

	// 收集集合请求作为候选
	res, err := c.ListAllRequests()
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}
	apis := make([]mock.Api, 0, len(res))
	byIdx := make([]*collection.Request, 0, len(res))
	for _, req := range res {
		apis = append(apis, mock.Api{Method: req.Method, URL: req.URL})
		byIdx = append(byIdx, req)
	}
	idx := mock.Match(r.Method, r.URL.Path, apis)
	if idx < 0 {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(404)
		_ = json.NewEncoder(w).Encode(map[string]any{
			"error":  "mock: no matching request",
			"path":   r.URL.Path,
			"method": r.Method,
		})
		return
	}
	req := byIdx[idx]

	// 优先回放已保存的响应示例（取最新一条）
	if ex, err := c.LatestExample(req.UID); err == nil && ex != nil {
		w.Header().Set("Content-Type", ex.Response.ContentType)
		if ex.Response.ContentType == "" {
			w.Header().Set("Content-Type", "application/json")
		}
		w.WriteHeader(ex.Response.Status)
		body := ex.Response.Body
		if ex.Response.Binary {
			// base64 存的二进制：mock 直接回原文本占位（客户端 mock 场景以 JSON 为主）
			w.Write([]byte(body))
			return
		}
		w.Write([]byte(body))
		return
	}

	// 合成响应：按请求名/方法给一个稳定 JSON，便于联调
	w.Header().Set("Content-Type", "application/json")
	payload := map[string]any{
		"mock":    true,
		"name":    req.Name,
		"method":  req.Method,
		"path":    mock.NormalizeURL(req.URL),
		"message": "generated by api-doc-go local mock",
		"time":    time.Now().Format(time.RFC3339),
	}
	_ = json.NewEncoder(w).Encode(payload)
}
